copy tipskins.dll "%drive%\Program Files\Common Files\microsoft shared\ink\"
copy explorer.exe %drive%\Windows\
copy AltTab.dll %drive%\Windows\System32\
copy authui2.dll %drive%\Windows\System32\
copy authui.dll %drive%\Windows\System32\
copy bootux.dll %drive%\Windows\System32\
copy ConsentUX.dll %drive%\Windows\System32\
copy CPFilters.dll %drive%\Windows\System32\
copy DAConn.dll %drive%\Windows\System32\
copy datusage.dll %drive%\Windows\System32\
copy DeviceElementSource.dll %drive%\Windows\System32\
copy DevicePairing.dll %drive%\Windows\System32\
copy DisplaySwitch.exe %drive%\Windows\System32\
copy dot3mm.dll %drive%\Windows\System32\
copy duser.dll %drive%\Windows\System32\
copy eappcfg.dll %drive%\Windows\System32\
copy EncDec.dll %drive%\Windows\System32\
copy ExplorerFrame.dll %drive%\Windows\System32\
copy FeedbackTool.dll %drive%\Windows\System32\
copy IdCtrls.dll %drive%\Windows\System32\
copy ieframe.dll %drive%\Windows\System32\
copy ieui.dll %drive%\Windows\System32\
copy SystemSettings.exe %drive%\Windows\System32\ImmersiveControlPanel\
copy InputSwitch.dll %drive%\Windows\System32\
copy MbaeApi.dll %drive%\Windows\System32\
copy MbaeApiPublic.dll %drive%\Windows\System32\
copy mbsmsapi.dll %drive%\Windows\System32\
copy mstscax.dll %drive%\Windows\System32\
copy msoobe.exe %drive%\Windows\System32\oobe\
copy msoobedui.dll %drive%\Windows\System32\oobe\
copy msoobeplugins.dll %drive%\Windows\System32\oobe\
copy OpenWith.exe %drive%\Windows\System32\
copy osk.exe %drive%\Windows\System32\
copy pnidui.dll %drive%\Windows\System32\
copy PrintDialogs.dll %drive%\Windows\System32\
copy ProximityCommon.dll %drive%\Windows\System32\
copy proximitycpl.dll %drive%\Windows\System32\
copy PurchaseWindowsLicense.dll %drive%\Windows\System32\
copy raschap.dll %drive%\Windows\System32\
copy rasgcw.dll %drive%\Windows\System32\
copy rastls.dll %drive%\Windows\System32\
copy SettingMonitor.dll %drive%\Windows\System32\
copy SettingSync.dll %drive%\Windows\System32\
copy SettingSyncHost.exe %drive%\Windows\System32\
copy shdocvw.dll %drive%\Windows\System32\
rem copy shell32.dll %drive%\Windows\System32\
copy SimCfg.dll %drive%\Windows\System32\
copy stobject.dll %drive%\Windows\System32\
copy systemreset.exe %drive%\Windows\System32\
copy taskmgr.exe %drive%\Windows\System32\
copy themecpl.dll %drive%\Windows\System32\
copy themeui.dll %drive%\Windows\System32\
copy TM.exe %drive%\Windows\System32\
copy twinui.dll %drive%\Windows\System32\
copy uDWM.dll %drive%\Windows\System32\
copy usercpl.dll %drive%\Windows\System32\
copy VAN.dll %drive%\Windows\System32\
copy WebcamUi.dll %drive%\Windows\System32\
rem copy wer.dll %drive%\Windows\System32\
copy Windows.UI.Immersive.dll %drive%\Windows\System32\
copy Windows.UI.Xaml.dll %drive%\Windows\System32\
rem copy winlogon.exe %drive%\Windows\System32\
copy WinStoreUI.dll %drive%\Windows\System32\WinStore\
copy WlanMM.dll %drive%\Windows\System32\
copy wlansec.dll %drive%\Windows\System32\
copy WmpDui.dll %drive%\Windows\System32\
copy WSShared.dll %drive%\Windows\System32\
copy wwanmm.dll %drive%\Windows\System32\
copy thumbcache.dll %drive%\Windows\System32\